language: python
python:
   - "2.7"

before_install:
   - sudo apt-get install libasound-dev

install:
   - pip install git+https://github.com/apixu/apixu-python.git -r requirements.txt

script:
   - python -m unittest discover tests -v "*_test.py"
